export const DEPARTMENT_OPTIONS = [
  'Bachelor of Science in Information Technology',
  'Bachelor of Science in Information Systems',
  'Bachelor of Science in Civil Engineering',
  'Bachelor of Science in Electrical Engineering',
  'Bachelor of Science in Industrial Technology',
  'Bachelor of Science in Agriculture',
  'Bachelor of Science in Fisheries',
  'Bachelor of Science in Forestry',
  'Bachelor of Science in Nursing',
  'Bachelor of Science in Business Administration',
  'Bachelor of Science in Accountancy',
  'Bachelor of Science in Hospitality Management',
  'Bachelor of Science in Tourism Management',
  'Bachelor of Arts in Communication',
  'Bachelor of Arts in Political Science',
  'Bachelor of Elementary Education',
  'Bachelor of Secondary Education',
  'Bachelor of Science in Criminology',
];

export const YEAR_LEVEL_OPTIONS = ['I', 'II', 'III', 'IV'];

export const SPORT_OPTIONS = [
  'Volleyball Women',
  'Volleyball Men',
  'Basketball Women',
  'Basketball Men',
  'Beach Volleyball Women',
  'Beach Volleyball Men',
  'Badminton Women',
  'Badminton Men',
  'Table Tennis Women',
  'Table Tennis Men',
  'Lawn Tennis Women',
  'Lawn Tennis Men',
  'Sepak Takraw Women',
  'Sepak Takraw Men',
  'Athletics Women',
  'Athletics Men',
  'Swimming Women',
  'Swimming Men',
  'Chess Women',
  'Chess Men',
  'Taekwondo Women',
  'Taekwondo Men',
  'Arnis Women',
  'Arnis Men',
  'Dancesport',
  'Futsal Women',
  'Futsal Men',
  'Football Women',
  'Football Men',
  'Softball Women',
  'Softball Men',
  'Mobile Legends Women',
  'Mobile Legends Men',
];
