import {
  AlertTriangle,
  Bell,
  Calendar,
  Check,
  CheckCircle,
  ChevronRight,
  ClipboardList,
  Clock,
  Download,
  Eye,
  EyeOff,
  FileText,
  Folder,
  GraduationCap,
  Hammer,
  HardHat,
  House,
  Info,
  LayoutDashboard,
  Mail,
  Menu,
  Pencil,
  Phone,
  Plus,
  Search,
  Settings,
  Shield,
  Trash2,
  Trophy,
  Upload,
  User,
  Users,
  X,
  XCircle,
  Wrench,
  Dumbbell,
  BarChart3,
  ClipboardCheck,
  CircleUserRound,
  LogOut,
  Paperclip,
  Megaphone,
  Stethoscope,
  FileCheck2,
  FilePlus2,
  Filter,
  ArrowLeft,
  ArrowRight,
  RotateCcw,
  CircleAlert,
} from 'lucide-react';

const icons = {
  alert: AlertTriangle,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  barChart: BarChart3,
  bell: Bell,
  calendar: Calendar,
  check: Check,
  checkCircle: CheckCircle,
  chevronRight: ChevronRight,
  clipboard: ClipboardList,
  clipboardCheck: ClipboardCheck,
  clock: Clock,
  close: X,
  document: FileText,
  fileText: FileText,
  download: Download,
  dumbbell: Dumbbell,
  eye: Eye,
  eyeOff: EyeOff,
  fileCheck: FileCheck2,
  filePlus: FilePlus2,
  filter: Filter,
  folder: Folder,
  graduationCap: GraduationCap,
  hammer: Hammer,
  hardHat: HardHat,
  home: House,
  info: Info,
  layoutDashboard: LayoutDashboard,
  logout: LogOut,
  mail: Mail,
  megaphone: Megaphone,
  menu: Menu,
  paperclip: Paperclip,
  pencil: Pencil,
  phone: Phone,
  plus: Plus,
  rotateCcw: RotateCcw,
  search: Search,
  settings: Settings,
  shield: Shield,
  stethoscope: Stethoscope,
  trash: Trash2,
  trophy: Trophy,
  upload: Upload,
  user: User,
  userCircle: CircleUserRound,
  users: Users,
  warning: CircleAlert,
  wrench: Wrench,
  xCircle: XCircle,
};

const Icon = ({ name, size = 20, strokeWidth = 1.75, className, ...props }) => {
  const IconComponent = icons[name] || Info;

  return (
    <IconComponent
      aria-hidden="true"
      focusable="false"
      size={size}
      strokeWidth={strokeWidth}
      className={className}
      {...props}
    />
  );
};

export default Icon;
